### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by Bartuzen**

### CODE REVIEW

**Comment by aggalex** [comment]
I already do have Turkish translations. Are you sure yours are better?

**Comment by Bartuzen** [comment]
I translate it first but you accept other one? Amazing.

**Comment by aggalex** [comment]
I have no context on who translated first 😅️. The translation is however up there. If you really feel like your translation fits the purpose better (objectively) then you can update it. It's not about who did what first, it's about who has done a better job on a certain field. I'm sorry if I hurt your feelings, I just couldn't notice your request on time. If you still feel that this still is not fair, I'll check the time difference between your contribution and the previous one I merged, and I'll act accordingly. But you have to understand that this will not benefit the project very much.

**Comment by aggalex** [comment]
Please respond if I should close this pull request or not

**Pull request closed without merging**
